### ISSUE TITLE
2.5.0 does not compile on CentOS 7.5.1804

### ISSUE THREAD

**Issue by hobbyman** [okbob/pspg#110]
Run configure, everything ok there.
Run make, get the following:

src/pgclient.c: In function 'pg_exec_query':
src/pgclient.c:231:2: warning: implicit declaration of function 'offsetof' [-Wimplicit-function-declaration]
  row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
  ^
src/pgclient.c:231:24: error: expected expression before 'RowType'
  row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
                        ^
src/pgclient.c:268:25: error: expected expression before 'RowType'
   row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
                         ^
make: *** [pgclient.o] Error 1

make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

**Comment by okbob** [comment]
Hi

čt 31. 10. 2019 v 13:27 odesílatel hobbyman <notifications@github.com>
napsal:

> Run configure, everything ok there.
> Run make, get the following:
>
> src/pgclient.c: In function 'pg_exec_query':
> src/pgclient.c:231:2: warning: implicit declaration of function 'offsetof'
> [-Wimplicit-function-declaration]
> row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
> ^
> src/pgclient.c:231:24: error: expected expression before 'RowType'
> row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
> ^
> src/pgclient.c:268:25: error: expected expression before 'RowType'
> row = malloc(offsetof(RowType, fields) + (nfields * sizeof(char *)));
> ^
> make: *** [pgclient.o] Error 1
>
> make --version
> GNU Make 3.82
> Built for x86_64-redhat-linux-gnu
>
> gcc --version
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
>
I inserted a #include <stddef.h>

it should to fix this issue. Please, try to use fresh master branch

Regards

Pavel

**Comment by hobbyman** [comment]
compiles and works great now. thanks!

**Comment by okbob** [comment]
pá 1. 11. 2019 v 11:50 odesílatel hobbyman <notifications@github.com>
napsal:

> compiles and works great now. thanks!
>

Thank you for info

Pavel
